name: Comment on Pull Requests included in Release
description: Comments on pull requests included in a GitHub release.
inputs:
  token:
    description: "GitHub access token"
    required: true
  message:
    description: "The message to be included in the comment"
    required: false
runs:
  using: "node16"
  main: "dist/index.js"
