name: Comment on Pull Requests included in Release
description: Comments on pull requests included in a GitHub release.
inputs:
  token:
    description: "GitHub access token"
    required: true
runs:
  using: "node16"
  main: "index.js"
